app/webapp/__init__.py
'''The blueprint for the web interface.

Includes all routes used by the web interface, as well as associated
html templates and static files.
'''

from flask import Blueprint
from . import routes


bp = Blueprint('webapp', __name__, template_folder='templates')
routes.register(bp)

app/webapp/routes.py
from flask import request, render_template, redirect, flash, current_app
from markupsafe import Markup
from app import core


def register(bp):
    @bp.route('/', methods=['GET', 'POST'])
    def index():
        if request.method == 'POST':
            # the form to shorten a URL was submitted
            try:
                short_key = core.shorten_url(request.form['url'])
                short_url = 'http://{}/{}'.format(
                    current_app.config['DOMAIN_NAME'],
                    short_key)
                short_url_markup = Markup('<a href="{0}">{0}</a>'.format(short_url))
                flash(short_url_markup, 'success')
            except core.InvalidURLError:
                flash('Invalid URL. Please try again.', 'error')
            except core.OutOfShortKeysError:
                flash('Unable to shorten URL, sorry!', 'error')
        return render_template('index.html')


    @bp.route('/<string:key>', methods=['GET'])
    def short_url_redirect(key):
        try:
            expanded_url = core.lengthen_url(key)
            if not expanded_url:
                return render_template('404.html'), 404
            # TODO this is just a temporary hack for domain-only URLs
            if not expanded_url.startswith('http'):
                expanded_url = 'http://' + expanded_url
            return redirect(expanded_url)
        except core.InvalidShortKeyError:
            return render_template('404.html'), 404

app/webapp/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
{% endblock %}

{% block title %}Shortcake{% endblock %}

{% block content %}
<div class="container" >
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/webapp/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/utils.html' as utils %}

{% block page_content %}
<div class="row" >
    <div class="col-md-8 col-md-offset-2" >
        <h1>Shortcake &mdash; Deliciously short URLs</h1>
        <form action="{{ url_for('webapp.index') }}" method="post" >
            <div class="input-group input-group-lg">
                <input type="text" class="form-control"
                    name="url" placeholder="Enter a URL to shorten" >
                <span class="input-group-btn" >
                    <button type="submit" class="btn btn-primary">
                        Shorten
                    </button>
                </span>
            </div>
        </form>
    </div>
</div>
<div id="flashed-messages" class="row" >
    <div class="col-md-8 col-md-offset-2" >
        {{ utils.flashed_messages(container=False) }}
    </div>
</div>
{% endblock %}